version: '3'
# networks:
#   default:
#     external:
#       name: k3snet
services:
  jumpserver:
    image: registry.cn-shenzhen.aliyuncs.com/infrastlabs/jumpserver:weak
    container_name: jumpserver
    restart: always
    privileged: true
    ports:
      - "8888:80"
      - "2222:22"
    networks:
      k3s_k3snet:
        ipv4_address: 3.4.5.100